# Model constants
MAX_HIDDEN_TAG_SIZE = 100
MAX_USERNAME_SIZE = 200
MAX_TAG_SIZE = 100
MAX_TITLE_SIZE = 200
MAX_COUNTRY_SIZE = 200
MAX_CITY_SIZE = 200
MAX_CONTINENT_SIZE = 200
MAX_PLACE_NAME_SIZE = 350
MAX_lOCATION_DIGITS = 9
LOCATION_DECIMAL_PLACES = 6

# Search and Recommendation constants
COEFF_LOCATION_SCORE = 2000
COEFF_TIME_SCORE = 10
COEFF_TIME_OVERLAPPED = 10
COEFF_COMMON_TAG_AMOUNT = 2
COEFF_COMMON_HIDDEN_TAG_AMOUNT = 1
COEFF_COMMON_WORDS_IN_TITLE_AMOUNT = 1
COEFF_ADMIRATION_SCORE_FOR_RECOMMENDATION = 0.75
COEFF_ADMIRATION_SCORE_FOR_SEARCH = 0.75
COEFF_COMPLETENESS_SCORE_FOR_RECOMMENDATION = 2
COEFF_COMPLETENESS_SCORE_FOR_SEARCH = 2
