# Completeness
COMPLETE_DESCRIPTION_NOUN_PHRASES = 5
COMPLETE_TAG_NUM = 2
COMPLETE_IMG_NUM = 1
COMPLETE_LOCATION = True

# Popularity Coefficients
COEFF_VIEW_SEC = 1
COEFF_NUM_COMMENTS = 1
COEFF_NUM_FAVORITES = 1
COEFF_COMPLETENESS = 1

# Trending Coefficients
COEFF_POPULARITY = 1
COEFF_FRESHNESS = 1

# Initial Popularity value to newly created items (in minutes)
INITIAL_FRESHNESS = 1500
