# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('atlas', '0002_cultural_heritage'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_media_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('cultural_heritage_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                             to='atlas.Cultural_Heritage')),
            ],
        ),
    ]
