# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('atlas', '0004_auto_20171021_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_media_item',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
