# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_image_media_item_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='cultural_heritage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='atlas.tag'),
        ),
    ]
