# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_auto_20171022_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='sound_media_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('cultural_heritage_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.Cultural_Heritage')),
            ],
        ),
        migrations.CreateModel(
            name='video_media_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('cultural_heritage_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.Cultural_Heritage')),
            ],
        ),
    ]
