# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlas', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.Cultural_Heritage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cultural_heritage',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', through='atlas.favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
