# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_auto_20171128_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultural_heritage',
            name='favorite_users',
        ),
    ]
