# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('atlas', '0008_auto_20171130_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_heritage',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cultural_heritage',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
