# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('atlas', '0009_auto_20171130_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_heritage',
            name='place_name',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
