# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0009_remove_cultural_heritage_favorite_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_heritage',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
