# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0010_cultural_heritage_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_heritage',
            name='favorited_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
