# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlas', '0011_auto_20171201_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('cultural_heritage_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.Cultural_Heritage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
