# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_auto_20171004_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
